version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app  # Optional: for local development to sync changes
    restart: always

# Optional volume section if you need persistent storage
# volumes:
#   node_modules:
