import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Layout from '@/components/Layout/Layout';
import StoreProvider from '@/components/Layout/Providers/StoreProvider';
import { Toaster } from '@/components/ui/toaster';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ivgam Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={nunito.className}>
          <Layout>{children}</Layout>
          <Toaster />
        </body>
      </html>
    </StoreProvider>
  );
}
