import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import Layout from '@/components/Layout/Layout';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
